### ISSUE TITLE
BaseEntryPeer not found

### ISSUE THREAD

**Issue by lionelbzv** [propelorm/PropelAclBundle#3]
I've got exactly the same behavior as explained in https://github.com/propelorm/PropelBundle/issues/343
I've read your explanations several times, but I can't figure how you don't have any problem.

Here is my security.yml conf:

```
# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    acl:
        provider:           propel.security.acl.provider

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
```

If I do a simple `app/console`, I've got this fatal:

```
PHP Fatal error:  Class 'Propel\Bundle\PropelAclBundle\Model\Acl\om\BaseEntryPeer' not found in /home/lionel/www/project.test.propel/vendor/propel/propel-acl-bundle/Model/Acl/EntryPeer.php on line 14
```

So i can't execute the `app/console propel:acl:init` to generate the om/map classes.
